# Generated by Django 5.0.2 on 2024-03-04 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='category',
        ),
    ]
